modules:
  - type: script
    scripts:
      - catppuccin.sh

  - type: files
    files:
      - source: system
        destination: /

  - type: bling
    install:
     - rpmfusion 

  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/akmods:main-42 / /tmp/akmods-common
      - RUN find /tmp/akmods-common
      # Install xone dep
      - RUN dnf copr enable -y ublue-os/akmods
      - RUN dnf install -y xone-kmod-common
      # Install ublue-os support package and akmods
      - RUN dnf install -y /tmp/akmods-common/rpms/ublue-os/ublue-os-akmods*.rpm
      - RUN dnf install -y /tmp/akmods-common/rpms/kmods/kmod-xone*.rpm

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - org.qutebrowser.qutebrowser
          - com.vivaldi.Vivaldi
          - com.github.tchx84.Flatseal
          - re.sonny.Junction
          - io.github.spacingbat3.webcord
          - io.podman_desktop.PodmanDesktop
          - org.angryip.ipscan
          - org.gnome.Firmware
          - org.onlyoffice.desktopeditors
          - io.missioncenter.MissionCenter
          - com.bitwarden.desktop
          - com.github.iwalton3.jellyfin-media-player
          - io.github.ilya_zlobintsev.LACT
        remove:
          - org.gnome.eog

  - type: dnf
    repos:
      copr:
        - ilyaz/LACT
    install:
      packages:
        - lact
        - alacritty
        - htop
        - slurp
        - pavucontrol
        - gnome-disk-utility
        - papirus-icon-theme
        - swaybg
        - wofi
        - udisks2
        - udiskie
        - tailscale
        - pamixer
        - network-manager-applet
        - brightnessctl 
        - bluez-tools
        - blueman
        - qt5-qtgraphicaleffects
        - qt5-qtquickcontrols2
        - qt5-qtsvg
        - qt5-qtwayland
        - qt6-qtwayland
        - kvantum
        - imv
        - p7zip
        - gvfs-mtp
        - gvfs-gphoto2
        - gvfs-smb
        - gvfs-nfs
        - gvfs-fuse
        - gvfs-archive
        - just
        - tlp
        - tlp-rdw
        - wireshark

  - type: systemd
    system:
      enabled:
        - sddm.service
        - tailscaled.service
        - sshd.service
        - tlp.service

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: signing

stages:
  - name: bluebuild
    from: docker.io/library/rust:1.77
    modules: # same as the top-level modules key, but executed in the custom stage
      - type: script
        no-cache: true
        snippets:
          - cargo install --locked --all-features blue-build
