modules:
  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/akmods:bazzite-42 /rpms /tmp/rpms
      - COPY --from=ghcr.io/ublue-os/akmods:bazzite-42 /kernel-rpms /tmp/rpms/kernel
      - RUN find /tmp/rpms
      - RUN rpm -q ublue-os-akmods-addons || rpm-ostree install /tmp/rpms/ublue-os/ublue-os-akmods-addons*.rpm
  - type: script
    snippets:
      - "curl -fsSL 'https://raw.githubusercontent.com/wayblueorg/wayblue/refs/heads/live/files/scripts/installsignedkernel.sh' | bash"
    scripts:
      - catppuccin.sh
   
  - type: files
    files:
      - source: system
        destination: /

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        repo:
          title: Flathub (system)
        install:
          - org.qutebrowser.qutebrowser
          - com.vivaldi.Vivaldi
          - com.github.tchx84.Flatseal
          - re.sonny.Junction
          - io.github.spacingbat3.webcord
          - io.podman_desktop.PodmanDesktop
          - org.angryip.ipscan
          - org.gnome.Firmware
          - org.onlyoffice.desktopeditors
          - io.missioncenter.MissionCenter
          - com.bitwarden.desktop
          - com.github.iwalton3.jellyfin-media-player
          - io.github.ilya_zlobintsev.LACT
        remove:
          - org.gnome.eog

  - type: dnf
    repos:
      copr:
        - ilyaz/LACT
    install:
      packages:
        - lact
        - alacritty
        - htop
        - stow
        - papirus-icon-theme
        - swaybg
        - udisks2
        - udiskie
        - tailscale
        - qt5-qtgraphicaleffects
        - qt5-qtquickcontrols2
        - qt5-qtsvg
        - kvantum
        - tlp
        - tlp-rdw
        - wireshark

  - type: systemd
    system:
      enabled:
        - sddm.service
        - tailscaled.service
        - sshd.service
        - tlp.service

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: signing

stages:
  - name: bluebuild
    from: docker.io/library/rust:1.77
    modules: # same as the top-level modules key, but executed in the custom stage
      - type: script
        no-cache: true
        snippets:
          - cargo install --locked --all-features blue-build
