stages:
  - name: bluebuild
    from: docker.io/library/rust:1.77
    modules: # same as the top-level modules key, but executed in the custom stage
      - type: script
        no-cache: true
        snippets:
          - cargo install --locked --all-features blue-build

modules:
  - type: script
    scripts:
      - catppuccin.sh

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.vivaldi.Vivaldi
        - com.github.tchx84.Flatseal
        - io.github.spacingbat3.webcord
        - com.valvesoftware.Steam
        - net.davidotek.pupgui2
        - com.bitwarden.desktop
      remove:
        - org.gnome.eog

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/pgdev/ghostty/repo/fedora-%OS_VERSION%/pgdev-ghosty-fedora-%OS_VERSION%.repo 
    install:
      - xdg-desktop-portal-gtk
      - ghostty
      - swaybg
      - wofi
      - udisks2
      - udiskie
      - htop
      - tailscale
    remove:
      - firefox
      - firefox-langpacks

  - type: files
    files:
      - source: system
        destination: /

  - type: systemd
    system:
      enabled:
        - sshd.service
        - tailscaled.service

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: signing
