name: ublue-hyprland
description: This is a Fedora Silverblue Hyprland OS image.

base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

modules:
  - type: script
    scripts:
      - catppuccin.sh
      - pyprland.sh

  - type: files
    files:
      - etc: /etc 

  - type: rpm-ostree
    install:
      - alacritty
      - hyprcursor
      - swaybg
      - wofi
      - udisks2
      - udiskie
      - htop
      - gamescope
      - tailscale
      - wireshark
    remove:
      - firefox
      - firefox-langpacks

  - type: systemd
    system:
      enabled:
        - sshd.service
        - tailscaled.service

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: default-flatpaks
    notify: true
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      install:
        - com.vivaldi.Vivaldi
        - one.ablaze.floorp
        - com.github.tchx84.Flatseal
        - io.github.spacingbat3.webcord
        - com.valvesoftware.Steam
        - net.davidotek.pupgui2
        - com.bitwarden.desktop
        - org.gnome.Boxes
      remove:
        - org.gnome.eog

  - type: signing
