name: ublue-hyprland
description: This is a Fedora Silverblue Hyprland OS image.

base-image: ghcr.io/wayblueorg/hyprland
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install:
      - hyprcursor
      - swaybg
      - pavucontrol-qt
      - wofi
      - udisks2
      - udiskie
      - alacritty
    remove:
      - firefox
      - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.vivaldi.Vivaldi
        - one.ablaze.floorp
        - com.github.tchx84.Flatseal
        - com.discordapp.Discord
        - com.valvesoftware.Steam
        - net.davidotek.pupgui2
        - com.bitwarden.desktop
        - org.gnome.Boxes
      remove:
        - org.gnome.eog

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: scripts
    scripts:
      - catppuccin.sh

  - type: signing
