name: ublue-hyprland
description: This is a Fedora Silverblue Hyprland OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      install:
        - hyprland
        - xdg-desktop-portal-hyprland
        - hyprcursor
        - waybar
        - swaybg
        - pipewire
        - pipewire-pulseaudio
        - pavucontrol
        - blueman
        - network-manager-applet
        - papirus-icon-theme
        - wofi
        - dunst
        - grim
        - slurp
        - wl-clipboard
        - brightnessctl
        - udisks2
        - udiskie
        - alacritty
        - fish
      remove:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.vivaldi.Vivaldi
        - one.ablaze.floorp
        - com.github.tchx84.Flatseal
        - com.discordapp.Discord
        - com.valvesoftware.Steam
        - net.davidotek.pupgui2
        - com.bitwarden.desktop
        - org.gnome.Boxes
      remove:
        - org.gnome.eog

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: signing 

