# image will be published to ghcr.io/<user>/<name>
name: ublue-hyprland
description: This is a Fedora Silverblu Hyprland OS image.

base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - usr: /usr
      # put configuration files you want in /etc/ on a booted system
      # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
    install:
      - greetd
      - tuigreet
      - hyprland
      - xdg-desktop-portal-hyprland
      - hyprcursor
      - waybar
      - papirus-icon-theme
      - swaybg
      - wofi
      - dunst
      - grim
      - slurp
      - wl-clipboard
      - brightnessctl
      - usbutils # lsusb
      - udisks2
      - udiskie
      - alacritty
    remove:
      - firefox
      - firefox-langpacks

  - type: systemd
    system:
      enabled:
        - greetd.service

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.vivaldi.Vivaldi
        - one.ablaze.floorp//lightning
        - com.github.tchx84.Flatseal
        - com.discordapp.Discord
        - com.valvesoftware.Steam
        - net.davidotek.pupgui2
        - com.bitwarden.desktop
        - org.gnome.Boxes
        - com.vscodium.codium
      remove:
        - org.gnome.eog

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

